dist: xenial
language: python
python: "3.7"

stages:
  - test

matrix:
  include:
    - stage: test
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh

    - stage: test
      os: osx
      # Selection of Python version is not available via language: on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh

install:
  - bash ~/miniconda.sh -b
  - python3 -m pip list
  - python3 -m pip install --upgrade git+https://github.com/pypa/virtualenv.git@refs/pull/1749/merge
  - virtualenv -vvv --with-traceback -p python3 .venv
  - . .venv/bin/activate

script:
  - cat ~/miniconda3/bin/conda
  - env
  - ~/miniconda3/bin/conda --version
  - ~/miniconda3/bin/python -c 'import sys; print(sys.path); print(sys.prefix)'
  - python3 -c "import subprocess; subprocess.check_call(['$HOME/miniconda3/bin/conda', '--version'])" || echo "This failed!"
  - python3 -c "import os; import subprocess; os.environ['__PYVENV_LAUNCHER__'] = ''; subprocess.check_call(['$HOME/miniconda3/bin/conda', '--version'])"
  - deactivate
  - python3 -c "import subprocess; subprocess.check_call(['$HOME/miniconda3/bin/conda', '--version'])"
