dist: xenial
language: python
python: "2.7"

stages:
  - test

matrix:
    - stage: test
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7-dev
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh

    - stage: test
      os: osx
      # No version of Python is available via language: on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      before_install:
        - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh

install:
  - python -m pip install "tox>=1.8.0"
  - virtualenv -p python3 .venv
  - . .venv/bin/activate
  - bash ~/miniconda.sh -b

script:
  - cat ~/miniconda3/bin/conda
  - env
  - ~/miniconda3/bin/conda --version
  - ~/miniconda3/bin/python -c 'import sys; print(sys.path); print(sys.prefix)'
  - python -c "import subprocess; subprocess.check_call(['$HOME/miniconda3/bin/conda', '--version'])"
  - deactivate
  - python -c "import subprocess; subprocess.check_call(['$HOME/miniconda3/bin/conda', '--version'])"
